name: CI
on: [push]
jobs:
  build:
    name: Test node@${{ matrix.node }}, ${{ matrix.os }}, react@${{ matrix.react }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x', '14.x', '16.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        react: ['^16.11', '^17.0.2', '^18']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Install react version
        run: |
          yarn add react@${{ matrix.react }} react-dom@${{ matrix.react }}

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs
        if: matrix.os == 'ubuntu-latest' && matrix.node == '16.x' && matrix.react == '^18'
